import Head from 'next/head'
import Navigation from '../components/Navigation/Navigation';
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Icarus - Hi-tech, Gear shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}> 
        <Navigation />       
      </main>
    </>
  )
}
